blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/eqYhuFzuKN
    about: Join our Discord server for discussions and support (MANDATORY for all contributors)
  - name: Stability Nexus's Website
    url: https://aossie.org/
    about: Learn more about us
